# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1021, 688)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_5.setObjectName("label_5")
        self.verticalLayout_14.addWidget(self.label_5)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setObjectName("label_7")
        self.verticalLayout_14.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_14.addWidget(self.label_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_14)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.feedBack1 = QtWidgets.QCheckBox(self.centralwidget)
        self.feedBack1.setObjectName("feedBack1")
        self.verticalLayout.addWidget(self.feedBack1)
        self.voltOut1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltOut1.setToolTip("")
        self.voltOut1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltOut1.setSuffix("")
        self.voltOut1.setDecimals(3)
        self.voltOut1.setMinimum(-10.0)
        self.voltOut1.setMaximum(10.0)
        self.voltOut1.setSingleStep(0.001)
        self.voltOut1.setProperty("value", 0.0)
        self.voltOut1.setObjectName("voltOut1")
        self.verticalLayout.addWidget(self.voltOut1)
        self.voltIn1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltIn1.setToolTip("")
        self.voltIn1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltIn1.setSuffix("")
        self.voltIn1.setDecimals(3)
        self.voltIn1.setMinimum(-10.0)
        self.voltIn1.setMaximum(10.0)
        self.voltIn1.setSingleStep(0.001)
        self.voltIn1.setProperty("value", 0.0)
        self.voltIn1.setObjectName("voltIn1")
        self.verticalLayout.addWidget(self.voltIn1)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.feedBack2 = QtWidgets.QCheckBox(self.centralwidget)
        self.feedBack2.setObjectName("feedBack2")
        self.verticalLayout_2.addWidget(self.feedBack2)
        self.voltOut2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltOut2.setToolTip("")
        self.voltOut2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltOut2.setSuffix("")
        self.voltOut2.setDecimals(3)
        self.voltOut2.setMinimum(-10.0)
        self.voltOut2.setMaximum(10.0)
        self.voltOut2.setSingleStep(0.001)
        self.voltOut2.setProperty("value", 0.0)
        self.voltOut2.setObjectName("voltOut2")
        self.verticalLayout_2.addWidget(self.voltOut2)
        self.voltIn2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltIn2.setToolTip("")
        self.voltIn2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltIn2.setSuffix("")
        self.voltIn2.setDecimals(3)
        self.voltIn2.setMinimum(-10.0)
        self.voltIn2.setMaximum(10.0)
        self.voltIn2.setSingleStep(0.001)
        self.voltIn2.setProperty("value", 0.0)
        self.voltIn2.setObjectName("voltIn2")
        self.verticalLayout_2.addWidget(self.voltIn2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.feedBack3 = QtWidgets.QCheckBox(self.centralwidget)
        self.feedBack3.setObjectName("feedBack3")
        self.verticalLayout_3.addWidget(self.feedBack3)
        self.voltOut3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltOut3.setToolTip("")
        self.voltOut3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltOut3.setSuffix("")
        self.voltOut3.setDecimals(3)
        self.voltOut3.setMinimum(-10.0)
        self.voltOut3.setMaximum(10.0)
        self.voltOut3.setSingleStep(0.001)
        self.voltOut3.setProperty("value", 0.0)
        self.voltOut3.setObjectName("voltOut3")
        self.verticalLayout_3.addWidget(self.voltOut3)
        self.voltIn3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltIn3.setToolTip("")
        self.voltIn3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltIn3.setSuffix("")
        self.voltIn3.setDecimals(3)
        self.voltIn3.setMinimum(-10.0)
        self.voltIn3.setMaximum(10.0)
        self.voltIn3.setSingleStep(0.001)
        self.voltIn3.setProperty("value", 0.0)
        self.voltIn3.setObjectName("voltIn3")
        self.verticalLayout_3.addWidget(self.voltIn3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.feedBack4 = QtWidgets.QCheckBox(self.centralwidget)
        self.feedBack4.setObjectName("feedBack4")
        self.verticalLayout_4.addWidget(self.feedBack4)
        self.voltOut4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltOut4.setToolTip("")
        self.voltOut4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltOut4.setSuffix("")
        self.voltOut4.setDecimals(3)
        self.voltOut4.setMinimum(-10.0)
        self.voltOut4.setMaximum(10.0)
        self.voltOut4.setSingleStep(0.001)
        self.voltOut4.setProperty("value", 0.0)
        self.voltOut4.setObjectName("voltOut4")
        self.verticalLayout_4.addWidget(self.voltOut4)
        self.voltIn4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltIn4.setToolTip("")
        self.voltIn4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltIn4.setSuffix("")
        self.voltIn4.setDecimals(3)
        self.voltIn4.setMinimum(-10.0)
        self.voltIn4.setMaximum(10.0)
        self.voltIn4.setSingleStep(0.001)
        self.voltIn4.setProperty("value", 0.0)
        self.voltIn4.setObjectName("voltIn4")
        self.verticalLayout_4.addWidget(self.voltIn4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_11.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_8.setObjectName("label_8")
        self.verticalLayout_15.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_10.setObjectName("label_10")
        self.verticalLayout_15.addWidget(self.label_10)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_9.setObjectName("label_9")
        self.verticalLayout_15.addWidget(self.label_9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_15)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.feedBack5 = QtWidgets.QCheckBox(self.centralwidget)
        self.feedBack5.setObjectName("feedBack5")
        self.verticalLayout_7.addWidget(self.feedBack5)
        self.voltOut5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltOut5.setToolTip("")
        self.voltOut5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltOut5.setSuffix("")
        self.voltOut5.setDecimals(3)
        self.voltOut5.setMinimum(-10.0)
        self.voltOut5.setMaximum(10.0)
        self.voltOut5.setSingleStep(0.001)
        self.voltOut5.setProperty("value", 0.0)
        self.voltOut5.setObjectName("voltOut5")
        self.verticalLayout_7.addWidget(self.voltOut5)
        self.voltIn5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltIn5.setToolTip("")
        self.voltIn5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltIn5.setSuffix("")
        self.voltIn5.setDecimals(3)
        self.voltIn5.setMinimum(-10.0)
        self.voltIn5.setMaximum(10.0)
        self.voltIn5.setSingleStep(0.001)
        self.voltIn5.setProperty("value", 0.0)
        self.voltIn5.setObjectName("voltIn5")
        self.verticalLayout_7.addWidget(self.voltIn5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.feedBack6 = QtWidgets.QCheckBox(self.centralwidget)
        self.feedBack6.setObjectName("feedBack6")
        self.verticalLayout_8.addWidget(self.feedBack6)
        self.voltOut6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltOut6.setToolTip("")
        self.voltOut6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltOut6.setSuffix("")
        self.voltOut6.setDecimals(3)
        self.voltOut6.setMinimum(-10.0)
        self.voltOut6.setMaximum(10.0)
        self.voltOut6.setSingleStep(0.001)
        self.voltOut6.setProperty("value", 0.0)
        self.voltOut6.setObjectName("voltOut6")
        self.verticalLayout_8.addWidget(self.voltOut6)
        self.voltIn6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltIn6.setToolTip("")
        self.voltIn6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltIn6.setSuffix("")
        self.voltIn6.setDecimals(3)
        self.voltIn6.setMinimum(-10.0)
        self.voltIn6.setMaximum(10.0)
        self.voltIn6.setSingleStep(0.001)
        self.voltIn6.setProperty("value", 0.0)
        self.voltIn6.setObjectName("voltIn6")
        self.verticalLayout_8.addWidget(self.voltIn6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.feedBack7 = QtWidgets.QCheckBox(self.centralwidget)
        self.feedBack7.setObjectName("feedBack7")
        self.verticalLayout_9.addWidget(self.feedBack7)
        self.voltOut7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltOut7.setToolTip("")
        self.voltOut7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltOut7.setSuffix("")
        self.voltOut7.setDecimals(3)
        self.voltOut7.setMinimum(-10.0)
        self.voltOut7.setMaximum(10.0)
        self.voltOut7.setSingleStep(0.001)
        self.voltOut7.setProperty("value", 0.0)
        self.voltOut7.setObjectName("voltOut7")
        self.verticalLayout_9.addWidget(self.voltOut7)
        self.voltIn7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltIn7.setToolTip("")
        self.voltIn7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltIn7.setSuffix("")
        self.voltIn7.setDecimals(3)
        self.voltIn7.setMinimum(-10.0)
        self.voltIn7.setMaximum(10.0)
        self.voltIn7.setSingleStep(0.001)
        self.voltIn7.setProperty("value", 0.0)
        self.voltIn7.setObjectName("voltIn7")
        self.verticalLayout_9.addWidget(self.voltIn7)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.feedBack8 = QtWidgets.QCheckBox(self.centralwidget)
        self.feedBack8.setObjectName("feedBack8")
        self.verticalLayout_10.addWidget(self.feedBack8)
        self.voltOut8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltOut8.setToolTip("")
        self.voltOut8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltOut8.setSuffix("")
        self.voltOut8.setDecimals(3)
        self.voltOut8.setMinimum(-10.0)
        self.voltOut8.setMaximum(10.0)
        self.voltOut8.setSingleStep(0.001)
        self.voltOut8.setProperty("value", 0.0)
        self.voltOut8.setObjectName("voltOut8")
        self.verticalLayout_10.addWidget(self.voltOut8)
        self.voltIn8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.voltIn8.setToolTip("")
        self.voltIn8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.voltIn8.setSuffix("")
        self.voltIn8.setDecimals(3)
        self.voltIn8.setMinimum(-10.0)
        self.voltIn8.setMaximum(10.0)
        self.voltIn8.setSingleStep(0.001)
        self.voltIn8.setProperty("value", 0.0)
        self.voltIn8.setObjectName("voltIn8")
        self.verticalLayout_10.addWidget(self.voltIn8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.gridLayout.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_13, 2, 1, 1, 1)
        self.vInPlotWidget = CustomWidget(self.centralwidget)
        self.vInPlotWidget.setMinimumSize(QtCore.QSize(0, 300))
        self.vInPlotWidget.setObjectName("vInPlotWidget")
        self.gridLayout.addWidget(self.vInPlotWidget, 0, 0, 1, 1)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_12.setSpacing(12)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label.setObjectName("label")
        self.verticalLayout_12.addWidget(self.label)
        self.ACin1 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ACin1.setToolTip("")
        self.ACin1.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ACin1.setSuffix("")
        self.ACin1.setDecimals(3)
        self.ACin1.setMinimum(-100.0)
        self.ACin1.setMaximum(100.0)
        self.ACin1.setSingleStep(0.001)
        self.ACin1.setProperty("value", 0.0)
        self.ACin1.setObjectName("ACin1")
        self.verticalLayout_12.addWidget(self.ACin1)
        self.ACin2 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ACin2.setToolTip("")
        self.ACin2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ACin2.setSuffix("")
        self.ACin2.setDecimals(3)
        self.ACin2.setMinimum(-100.0)
        self.ACin2.setMaximum(100.0)
        self.ACin2.setSingleStep(0.001)
        self.ACin2.setProperty("value", 0.0)
        self.ACin2.setObjectName("ACin2")
        self.verticalLayout_12.addWidget(self.ACin2)
        self.ACin3 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ACin3.setToolTip("")
        self.ACin3.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ACin3.setSuffix("")
        self.ACin3.setDecimals(3)
        self.ACin3.setMinimum(-100.0)
        self.ACin3.setMaximum(100.0)
        self.ACin3.setSingleStep(0.001)
        self.ACin3.setProperty("value", 0.0)
        self.ACin3.setObjectName("ACin3")
        self.verticalLayout_12.addWidget(self.ACin3)
        self.ACin4 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ACin4.setToolTip("")
        self.ACin4.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ACin4.setSuffix("")
        self.ACin4.setDecimals(3)
        self.ACin4.setMinimum(-100.0)
        self.ACin4.setMaximum(100.0)
        self.ACin4.setSingleStep(0.001)
        self.ACin4.setProperty("value", 0.0)
        self.ACin4.setObjectName("ACin4")
        self.verticalLayout_12.addWidget(self.ACin4)
        self.ACin5 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ACin5.setToolTip("")
        self.ACin5.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ACin5.setSuffix("")
        self.ACin5.setDecimals(3)
        self.ACin5.setMinimum(-100.0)
        self.ACin5.setMaximum(100.0)
        self.ACin5.setSingleStep(0.001)
        self.ACin5.setProperty("value", 0.0)
        self.ACin5.setObjectName("ACin5")
        self.verticalLayout_12.addWidget(self.ACin5)
        self.ACin6 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ACin6.setToolTip("")
        self.ACin6.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ACin6.setSuffix("")
        self.ACin6.setDecimals(3)
        self.ACin6.setMinimum(-100.0)
        self.ACin6.setMaximum(100.0)
        self.ACin6.setSingleStep(0.001)
        self.ACin6.setProperty("value", 0.0)
        self.ACin6.setObjectName("ACin6")
        self.verticalLayout_12.addWidget(self.ACin6)
        self.ACin7 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ACin7.setToolTip("")
        self.ACin7.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ACin7.setSuffix("")
        self.ACin7.setDecimals(3)
        self.ACin7.setMinimum(-100.0)
        self.ACin7.setMaximum(100.0)
        self.ACin7.setSingleStep(0.001)
        self.ACin7.setProperty("value", 0.0)
        self.ACin7.setObjectName("ACin7")
        self.verticalLayout_12.addWidget(self.ACin7)
        self.ACin8 = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.ACin8.setToolTip("")
        self.ACin8.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.ACin8.setSuffix("")
        self.ACin8.setDecimals(3)
        self.ACin8.setMinimum(-10.0)
        self.ACin8.setMaximum(100.0)
        self.ACin8.setSingleStep(0.001)
        self.ACin8.setProperty("value", 0.0)
        self.ACin8.setObjectName("ACin8")
        self.verticalLayout_12.addWidget(self.ACin8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_12.addWidget(self.label_3)
        self.Kint = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Kint.setToolTip("")
        self.Kint.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Kint.setSuffix("")
        self.Kint.setDecimals(3)
        self.Kint.setMinimum(-10.0)
        self.Kint.setMaximum(10.0)
        self.Kint.setSingleStep(0.001)
        self.Kint.setProperty("value", 0.0)
        self.Kint.setObjectName("Kint")
        self.verticalLayout_12.addWidget(self.Kint)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_12.addWidget(self.label_2)
        self.Kprop = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.Kprop.setToolTip("")
        self.Kprop.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Kprop.setSuffix("")
        self.Kprop.setDecimals(3)
        self.Kprop.setMinimum(-10.0)
        self.Kprop.setMaximum(10.0)
        self.Kprop.setSingleStep(0.001)
        self.Kprop.setProperty("value", 0.0)
        self.Kprop.setObjectName("Kprop")
        self.verticalLayout_12.addWidget(self.Kprop)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_12.addWidget(self.label_4)
        self.averageVal = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.averageVal.setToolTip("")
        self.averageVal.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.averageVal.setSuffix("")
        self.averageVal.setDecimals(3)
        self.averageVal.setMinimum(1.0)
        self.averageVal.setMaximum(1000000.0)
        self.averageVal.setSingleStep(0.1)
        self.averageVal.setProperty("value", 1.0)
        self.averageVal.setObjectName("averageVal")
        self.verticalLayout_12.addWidget(self.averageVal)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_12.addWidget(self.label_11)
        self.referenceChannel = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.referenceChannel.sizePolicy().hasHeightForWidth())
        self.referenceChannel.setSizePolicy(sizePolicy)
        self.referenceChannel.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.referenceChannel.setMaximum(8)
        self.referenceChannel.setObjectName("referenceChannel")
        self.verticalLayout_12.addWidget(self.referenceChannel)
        self.gridLayout.addLayout(self.verticalLayout_12, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 2, 1, 1)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1021, 21))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "MainWindow"))
        self.label_5.setText(_translate("mainWindow", "feedback?"))
        self.label_7.setText(_translate("mainWindow", "output Volt"))
        self.label_6.setText(_translate("mainWindow", "input Volt"))
        self.feedBack1.setText(_translate("mainWindow", "chan 1"))
        self.feedBack2.setText(_translate("mainWindow", "chan 2"))
        self.feedBack3.setText(_translate("mainWindow", "chan 3"))
        self.feedBack4.setText(_translate("mainWindow", "chan 4"))
        self.label_8.setText(_translate("mainWindow", "feedback?"))
        self.label_10.setText(_translate("mainWindow", "output Volt"))
        self.label_9.setText(_translate("mainWindow", "input Volt"))
        self.feedBack5.setText(_translate("mainWindow", "chan 5"))
        self.feedBack6.setText(_translate("mainWindow", "chan 6"))
        self.feedBack7.setText(_translate("mainWindow", "chan 7"))
        self.feedBack8.setText(_translate("mainWindow", "chan 8"))
        self.label.setText(_translate("mainWindow", "AC values in"))
        self.label_3.setText(_translate("mainWindow", "Ki"))
        self.label_2.setText(_translate("mainWindow", "Kp"))
        self.label_4.setText(_translate("mainWindow", "Averaging"))
        self.label_11.setText(_translate("mainWindow", "Reference Channel (0 is no ref)"))

from Plotter import CustomWidget
